name: Code Style Check

on:
  push:
    branches: [develop]

jobs:
  lint:
    name: Check prettier and eslint
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --no-package-lock --force

      - name: Check prettier
        run: npm run format

      - name: Check eslint
        run: npm run lint
